In [1]:
import numpy as np
import EX4

dataset = EX4.clean_data('D:\\data visualition\\sample datasets\\london_visiters.csv')
dataset[:10]

[['2002',
  'January-March',
  'Belgium',
  '1-3  nights',
  'Air',
  'Holiday',
  ' LONDON',
  3.572185978,
  0.969138388,
  6.954456106,
  '5'],
 ['2002',
  'January-March',
  'Belgium',
  '1-3  nights',
  'Air',
  'Business',
  ' LONDON',
  9.284225881,
  2.399576575,
  12.60495917,
  '19'],
 ['2002',
  'January-March',
  'Belgium',
  '1-3  nights',
  'Air',
  'VFR',
  ' LONDON',
  0.877182007,
  0.089833103,
  2.153127983,
  '3'],
 ['2002',
  'January-March',
  'Belgium',
  '1-3  nights',
  'Air',
  'Miscellaneous',
  ' LONDON',
  0.163874,
  0.0101602,
  0.163874,
  '1'],
 ['2002',
  'January-March',
  'Belgium',
  '1-3  nights',
  'Sea',
  'Business',
  ' LONDON',
  1.648669958,
  0.016789,
  1.650300026,
  '1'],
 ['2002',
  'January-March',
  'Belgium',
  '1-3  nights',
  'Sea',
  'Miscellaneous',
  ' LONDON',
  0.590807021,
  0.0039525,
  1.772420049,
  '1'],
 ['2002',
  'January-March',
  'Belgium',
  '1-3  nights',
  'Tunnel',
  'Holiday',
  ' LONDON',
  10.94025093,
  2.7654

In [2]:
spends = [row[8] for row in dataset]
nights = [row[9] for row in dataset]
len(spends), len(nights)

(59804, 59804)

In [3]:
spends = np.array(spends)
spends[:10]

array([0.96913839, 2.39957658, 0.0898331 , 0.0101602 , 0.016789  ,
       0.0039525 , 2.76547272, 1.44669668, 0.46814016, 0.46572091])

In [4]:
nights = np.array(nights)
nights[:10]

array([ 6.95445611, 12.60495917,  2.15312798,  0.163874  ,  1.65030003,
        1.77242005, 23.24268785, 10.42855498,  9.44141591,  1.40989402])

In [5]:
spends_in_pounds = spends * 1000000
spends_in_pounds[:10]

array([ 969138.388, 2399576.575,   89833.103,   10160.2  ,   16789.   ,
          3952.5  , 2765472.721, 1446696.68 ,  468140.161,  465720.912])

In [6]:
spends_per_night = spends_in_pounds / nights
spends_per_night[:10]

array([139355.02262555, 190367.65947731,  41722.13807506,  62000.07322699,
        10173.30166363,   2230.00185663, 118982.48338778, 138724.55798282,
        49583.68169148, 330323.3475168 ])

In [8]:
np.log10(spends_per_night)

c:\users\ashen\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log10
  """Entry point for launching an IPython kernel.


array([5.14412263, 5.27959317, 4.62036656, ..., 4.83037479, 4.61891168,
       4.70774326])

In [18]:
sample = set([int(row[-1]) for row in dataset])
sample

{1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 157,
 158,
 162,
 163,
 164,
 165,
 166,
 167,
 169,
 170,
 171,
 174,
 175,
 176,
 177,
 178,
 180,
 181,
 182,
 185,
 186,
 189,
 190,
 191,
 192,
 194,
 197,
 200,
 206,
 207,
 212,
 213,
 219,
 222,
 223,
 227,
 229

In [25]:
visitor_dtl = np.array([[row[8], row[9], int(row[10])] for row in dataset])
visitor_dtl[:10]

array([[9.69138388e-01, 6.95445611e+00, 5.00000000e+00],
       [2.39957658e+00, 1.26049592e+01, 1.90000000e+01],
       [8.98331030e-02, 2.15312798e+00, 3.00000000e+00],
       [1.01602000e-02, 1.63874000e-01, 1.00000000e+00],
       [1.67890000e-02, 1.65030003e+00, 1.00000000e+00],
       [3.95250000e-03, 1.77242005e+00, 1.00000000e+00],
       [2.76547272e+00, 2.32426878e+01, 3.00000000e+01],
       [1.44669668e+00, 1.04285550e+01, 1.60000000e+01],
       [4.68140161e-01, 9.44141591e+00, 1.30000000e+01],
       [4.65720912e-01, 1.40989402e+00, 2.00000000e+00]])

In [28]:
dimension = visitor_dtl.ndim
size = visitor_dtl.size
shape = visitor_dtl.shape
dataType = visitor_dtl.dtype

print(f'dimension: {dimension}, size: {size}, shape: {shape}, data type: {dataType}')

dimension: 2, size: 179412, shape: (59804, 3), data type: float64


In [30]:
np.zeros((4,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [31]:
np.ones((4,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [32]:
np.eye((4), dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [39]:
data = np.random.randint(low=10, high=101, size=(4,3))
data

array([[91, 71, 84],
       [54, 90, 87],
       [17, 57, 63],
       [48, 87, 31]])

In [37]:
data.reshape(2, 2, 3)

array([[12, 82, 63],
       [57, 87, 16]])

In [38]:
data.reshape(3, 2, 2)

array([[[12, 82],
        [63, 57]],

       [[87, 16],
        [30, 70]],

       [[57, 98],
        [79, 88]]])

In [52]:
sub1 = np.random.randint(low=12, high=25, size=(3,3))
sub2 = np.random.randint(low=36, high=64, size=(4,3))
sub3 = sub2.reshape(1,3,4)

In [53]:
sub1

array([[18, 20, 14],
       [12, 12, 13],
       [18, 15, 22]])

In [54]:
sub2

array([[43, 52, 57],
       [46, 45, 38],
       [43, 49, 51],
       [45, 45, 45]])

In [55]:
sub3

array([[[43, 52, 57, 46],
        [45, 38, 43, 49],
        [51, 45, 45, 45]]])

In [58]:
np.vstack((sub1, sub2))

array([[18, 20, 14],
       [12, 12, 13],
       [18, 15, 22],
       [43, 52, 57],
       [46, 45, 38],
       [43, 49, 51],
       [45, 45, 45]])

In [59]:
np.hstack((sub1, sub3[0]))

array([[18, 20, 14, 43, 52, 57, 46],
       [12, 12, 13, 45, 38, 43, 49],
       [18, 15, 22, 51, 45, 45, 45]])